version: 2
jobs:
  build:
    working_directory: ~/dylan
    docker:
      - image: erlang:20.0.1
    environment:
      - MIX_ENV: test
        BASH_ENV: ".circleci/bash_env.sh"
    steps:
      - run: apt-get update
      - run: apt-get install git --yes
      - run: git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.3.0
      - run: asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
      - run: asdf elixir install master-otp-20

      # Clone project
      - checkout

      # Install deps
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix deps.compile

      # Compile

      # TODO: Re-enable with Elixir v1.5.1
      # Elixir v1.5.0 has a bug where a warning can erroneously emitted for a
      # with with an else block even.
      - run: mix compile #--warnings-as-errors

      # Test
      - run: mix test --trace # TODO: use coveralls
